# Generated by Django 4.1.4 on 2023-01-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
